<head>
<title>Ejemplo onclick jQuery</title>
<style type="text/css">
#Cuadrado{
  width: 100px;
  height: 100px;
  background: #2980b9;
  border-color: #FF622C;
  border-style: solid;
  border-radius: 25px;
}
</style>
<script src="http://code,jquery.com/jquery-1.12.4.min.js"></script>
<script type="text/javascript" src="../js/scriptefectos.js"></script>
</head>
<body>
  <div id="Cuadrado"></div>
  <p>
    <button id="Esconde">Esconder</button>
    <button id="Muestra">Mostrar</button>
</body>
</html>
